### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nyxsenka** [Coopyy/Unturned-Simple-External#3]
How can i make this work on linux?

**Comment by Coopyy** [comment]
change how you read/write memory

**Comment by nyxsenka** [comment]
> change how you read/write memory

Sir , can you give me example for linux if you have spare time

**Comment by Coopyy** [comment]
i will not, but i encourage you to look into other linux externals like
https://github.com/owerosu/linux-csgo-external/blob/master/remote.cpp
