### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by Blickyyy** [Coopyy/Unturned-Simple-External#4]
Is there anyway to update the actively holding weapons, so when i change the weapon the recoil and spread is set to 0 again..
I cant figure it out myself.

It works perfectly with my driver but i cant that to work..

**Comment by Coopyy** [comment]
putting it in a loop works fine for me
note its the asset and not the held gun itself, so 2 different instances of the same gun have the same asset
also these changed values never reset to the original unless you do it yourself

```c++
while (true)
{
	Sleep(1000);
	auto gun = (SDG::ItemGunAsset*)(localPlayer->equipment()->asset());
	printf("Current weapon: %p\n", gun);
	if (gun)
	{
		gun->recoilMax_x_set(0);
		gun->recoilMax_y_set(0);
		gun->recoilMin_x_set(0);
		gun->recoilMin_y_set(0);
		gun->baseSpreadAngleRadians_set(0);
		Log("Set current weapon recoil and spread to 0");
	}
	else
		Log("Couldn't find current weapon");
}
```

**Comment by Blickyyy** [comment]
ah okay.. thank you buddy!
Is it possible to always display the map?

**Comment by Coopyy** [comment]
search `hasGPS` in dnspy

**Comment by Blickyyy** [comment]
> putting it in a loop works fine for me note its the asset and not the held gun itself, so 2 different instances of the same gun have the same asset also these changed values never reset to the original unless you do it yourself
> 
> ```c++
> while (true)
> {
> 	Sleep(1000);
> 	auto gun = (SDG::ItemGunAsset*)(localPlayer->equipment()->asset());
> 	printf("Current weapon: %p\n", gun);
> 	if (gun)
> 	{
> 		gun->recoilMax_x_set(0);
> 		gun->recoilMax_y_set(0);
> 		gun->recoilMin_x_set(0);
> 		gun->recoilMin_y_set(0);
> 		gun->baseSpreadAngleRadians_set(0);
> 		Log("Set current weapon recoil and spread to 0");
> 	}
> 	else
> 		Log("Couldn't find current weapon");
> }
> ```

This would also work with Admin right?

**Comment by Coopyy** [comment]
> > putting it in a loop works fine for me note its the asset and not the held gun itself, so 2 different instances of the same gun have the same asset also these changed values never reset to the original unless you do it yourself
> > ```c++
> > while (true)
> > {
> > 	Sleep(1000);
> > 	auto gun = (SDG::ItemGunAsset*)(localPlayer->equipment()->asset());
> > 	printf("Current weapon: %p\n", gun);
> > 	if (gun)
> > 	{
> > 		gun->recoilMax_x_set(0);
> > 		gun->recoilMax_y_set(0);
> > 		gun->recoilMin_x_set(0);
> > 		gun->recoilMin_y_set(0);
> > 		gun->baseSpreadAngleRadians_set(0);
> > 		Log("Set current weapon recoil and spread to 0");
> > 	}
> > 	else
> > 		Log("Couldn't find current weapon");
> > }
> > ```
> 
> This would also work with Admin right?

yeah

**Comment by Blickyyy** [comment]
Like pretty much i have to search for the hasGPS offset and do the same as we did with norecoil?

**Comment by Coopyy** [comment]
all you need to "find offsets" is class and field names, which looking in dnspy would be `PlayerDashboardInformationUI.hasGPS`

**Comment by Blickyyy** [comment]
Yea sorry thats what ive ment

**Comment by Blickyyy** [comment]
```
       hasGPS = Classes::PlayerDashboardInformationUI->find_field("hasGPS")->offset();
		
	class PlayerDashboardInformationUI
	{

	public:

		Field<bool>* hasGPS();

	};
```

is this correct?

**Comment by Blickyyy** [comment]
not in the same file i know

**Comment by Coopyy** [comment]
i would update your repo btw, chaanged  a lot but yes that looks right

**Comment by Blickyyy** [comment]
> putting it in a loop works fine for me note its the asset and not the held gun itself, so 2 different instances of the same gun have the same asset also these changed values never reset to the original unless you do it yourself
> 
> ```c++
> while (true)
> {
> 	Sleep(1000);
> 	auto gun = (SDG::ItemGunAsset*)(localPlayer->equipment()->asset());
> 	printf("Current weapon: %p\n", gun);
> 	if (gun)
> 	{
> 		gun->recoilMax_x_set(0);
> 		gun->recoilMax_y_set(0);
> 		gun->recoilMin_x_set(0);
> 		gun->recoilMin_y_set(0);
> 		gun->baseSpreadAngleRadians_set(0);
> 		Log("Set current weapon recoil and spread to 0");
> 	}
> 	else
> 		Log("Couldn't find current weapon");
> }
> ```

but when i change the weapon for example from a maplestrike to sabertoth only the maplestrik have norecoil even if the "Current Weapon" change

**Comment by Coopyy** [comment]
> i would update your repo btw, chaanged a lot but yes that looks right

issue with older version, i tried to do something different with fields, but it causes issues
